; Rizom Temp — ESP32-C3 Super Mini Firmware
; Pinagem: DS18B20→GPIO2, OLED SDA→GPIO8, OLED SCL→GPIO9

[platformio]
src_dir = .

[env:esp32-c3-devkitm-1]
platform = espressif32
board = esp32-c3-devkitm-1
framework = arduino
monitor_speed = 115200
upload_speed = 460800
monitor_filters = esp32_exception_decoder, log2file
build_flags =
  -DCORE_DEBUG_LEVEL=0
board_build.partitions = default_4MB.csv
upload_protocol = esptool
lib_deps =
  PubSubClient @ ^2.8
  OneWire @ ^2.3.4
  DallasTemperature @ ^3.9.7
  Adafruit SSD1306 @ ^2.5.7
  Adafruit GFX Library @ ^1.11.9
  ArduinoJson @ ^7.0.4
