; Rizom Temp — ESP-01 Firmware
; Flash: GPIO0=GND no boot, adaptador USB-TTL 3.3V
; Pinagem: DS18B20 DATA → GPIO2 + pull-up 4.7kΩ → 3.3V

[platformio]
src_dir = .

[env:esp01]
platform = espressif8266
board = esp01_1m
framework = arduino
monitor_speed = 115200
upload_speed = 115200
lib_deps =
  PubSubClient @ ^2.8
  OneWire @ ^2.3.4
  DallasTemperature @ ^3.9.7
upload_port = /dev/cu.usbserial-1110     ; macOS
; upload_port = /dev/ttyUSB0              ; Linux
; upload_port = COM3                      ; Windows
