; Rizom Temp — Wemos D1 Mini (portal simples, sem MQTT)

[platformio]
src_dir = .

[env:d1_mini_portal_simples]
platform = espressif8266
board = d1_mini
framework = arduino
monitor_speed = 115200
upload_speed = 921600
lib_deps =
  OneWire @ ^2.3.4
  DallasTemperature @ ^3.9.7
