; Rizom Temp — Wemos D1 Mini Firmware
; Pinagem: DS18B20→D5(GPIO14), LED→D4(GPIO2), Reset→D3(GPIO0)

[platformio]
src_dir = .
data_dir = ../data

[env:d1_mini]
platform = espressif8266
board = d1_mini
framework = arduino
board_build.filesystem = littlefs
monitor_speed = 115200
upload_speed = 921600
lib_deps =
  PubSubClient @ ^2.8
  OneWire @ ^2.3.4
  DallasTemperature @ ^3.9.7
